# data
data:
  train_data: "/home/dmnph/Game-Time-Sushi/moshi-finetune/data/gametime_train_advanced_scores5_noTimeSilence.jsonl"
  eval_data: "/home/dmnph/Game-Time-Sushi/moshi-finetune/data/gametime_test_advanced.jsonl"
  shuffle: true

# model (load base from HF and warm start LoRA from previous run)
moshi_paths:
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"
  config_path: null
  moshi_path: null
  mimi_path: null
  tokenizer_path: null

# Optional warm-start adapter
lora_weight: "/home/dmnph/Game-Time-Sushi/saves/moshi/gametime_basic_lora/checkpoints/checkpoint_002500/consolidated/lora.safetensors"

full_finetuning: false  # keep LoRA for 24 GB TITAN RTX
lora:
  enable: true
  rank: 128
  scaling: 2.0
  ft_embed: false

first_codebook_weight_multiplier: 100.0
text_padding_weight: 0.5

# optim
duration_sec: 100
batch_size: 16        
max_steps: 5000         # ≈1.8 epochs over 16.9k clips
gradient_checkpointing: true
optim:
  lr: 2.0e-6
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 10
eval_freq: 250
do_eval: true
do_ckpt: true
ckpt_freq: 250

# num_microbatches: 1
# max_norm: 1.0
# param_dtype: bfloat16
# num_ckpt_keep: 3

save_adapters: true
run_dir: "../saves/moshi/gametime_adv_after_basic_scores5_nosilence_lora"

wandb:
  project: "moshi-gametime"
  run_name: "moshi_7B_gametime_adv_top_after_basic_scores5_nosilence_lora"
  key: "131f192f269eca7a738b239324dee215e74d2bb5"  
